In [1]:
import cv2 as cv
import numpy as np

# 1. Pixel processing

## 1.1 Binary image, grey scale image

In [3]:
# Binary image

img_black = np.zeros((8,8), dtype=np.uint8)
print("img_black=\n",img_black)
cv.imshow("one",img_black)
print("img_black[0,3] = ",img_black[0,3])

img_black[0,3] = 255
print("changed img_black[0,3] = ",img_black[0,3])

cv.imshow("two",img_black)
cv.waitKey()
cv.destroyAllWindows()

img_black=
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
img_black[0,3] =  0
changed img_black[0,3] =  255


In [5]:
# Gray scale image

panda = cv.imread("picture/panda.jpg",0) # 0 means gray scale
cv.imshow("before", panda)

for i in range(10, 100):
    for j in range(80, 100):
        panda[i, j]=255

cv.imshow("after", panda)
cv.waitKey()
cv.destroyAllWindows()

## 1.2 Colour images

In [6]:
# Blue channel
blue = np.zeros((300, 300, 3), dtype=np.uint8)
blue[:,:,0] = 255
print("blue=\n", blue)
cv.imshow("blue", blue)

# Green channel
green = np.zeros((300, 300, 3), dtype=np.uint8)
green[:,:,1] = 255
print("red=\n", green)
cv.imshow("green", green)

# Red channel
red = np.zeros((300, 300, 3), dtype=np.uint8)
red[:,:,2] = 255
print("red=\n", red)
cv.imshow("red", red)

cv.waitKey()
cv.destroyAllWindows()

blue=
 [[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]]
red=
 [[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0 

In [7]:
img = np.zeros((300, 300, 3), dtype=np.uint8)
img[:,0:100,0]=255
img[:,100:200,1]=255
img[:,200:300,2]=255
print("img=\n",img)
cv.imshow("img", img)
cv.waitKey()
cv.destroyAllWindows()

img=
 [[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]]


In [8]:
img = np.zeros((2,4,3), dtype=np.uint8)
print("img[0,3]=", img[0,3])
print("img[1,2,2]=", img[1,2,2])
img[0,3]=255
img[0,0]=[66,77,88]
img[1,1,1]=3
img[1,2,2]=4
img[0,2,0]=5
print("changed img\n", img)
print("changed img[1,2,2]", img[1,2,2])

img[0,3]= [0 0 0]
img[1,2,2]= 0
changed img
 [[[ 66  77  88]
  [  0   0   0]
  [  5   0   0]
  [255 255 255]]

 [[  0   0   0]
  [  0   3   0]
  [  0   0   4]
  [  0   0   0]]]
changed img[1,2,2] 4


In [9]:
panda = cv.imread("picture/panda.jpg")
cv.imshow("before", panda)
print("panda[0,0]=",panda[0,0])
print("panda[0,0,0]=",panda[0,0,0])
print("panda[0,0,1]=",panda[0,0,1])
print("panda[0,0,2]=",panda[0,0,2])
print("panda[50,0]=",panda[50,0])
print("panda[100,0]=",panda[100,0])

# area 1
for i in range (0,50):
    for j in range(0,100):
        for k in range(0,3):
            panda[i,j,k]=255 # white
            
# area 2
for i in range(50,100):
    for j in range(0,100):
        panda[i,j]=[128,128,128] # gray
        
#area 3
for i in range(100,150):
    for j in range(0,100):
        panda[i,j]=0 # black
        
cv.imshow("after",panda)
print("panda[0,0]=",panda[0,0])
print("panda[0,0,0]=",panda[0,0,0])
print("panda[0,0,1]=",panda[0,0,1])
print("panda[0,0,2]=",panda[0,0,2])
print("panda[50,0]=",panda[50,0])
print("panda[100,0]=",panda[100,0])
cv.waitKey()
cv.destroyAllWindows()

panda[0,0]= [255 255 255]
panda[0,0,0]= 255
panda[0,0,1]= 255
panda[0,0,2]= 255
panda[50,0]= [253 255 255]
panda[100,0]= [253 252 254]
panda[0,0]= [255 255 255]
panda[0,0,0]= 255
panda[0,0,1]= 255
panda[0,0,2]= 255
panda[50,0]= [128 128 128]
panda[100,0]= [0 0 0]


# 2. Accessing pixels using numpy.array

## 2.1 Gray images

In [15]:
img = np.random.randint(10, 99, size=[5,5], dtype=np.uint8)
print("img=\n",img)
print("img.item(3,2) = ", img.item(3,2))
img.itemset((3, 2), 255)
print("changed img=\n", img)
print("changed img.item(3, 2) = ", img.item(3,2))

img=
 [[76 76 73 36 44]
 [65 62 62 72 50]
 [64 15 42 75 60]
 [43 13 36 73 32]
 [37 18 85 69 19]]
img.item(3,2) =  36
changed img=
 [[ 76  76  73  36  44]
 [ 65  62  62  72  50]
 [ 64  15  42  75  60]
 [ 43  13 255  73  32]
 [ 37  18  85  69  19]]
changed img.item(3, 2) =  255


In [16]:
img = np.random.randint(0, 256, size = [256, 256], dtype = np.uint8)
cv.imshow("demo", img)
cv.waitKey()
cv.destroyAllWindows()

In [17]:
# Read
panda = cv.imread("picture/panda.jpg", 0)
print("img.item(3, 2) = ", panda.item(3, 2))
panda.itemset((3, 2), 255)
print("changed img.item(3, 2) = ", panda.item(3, 2))

# Modification
cv.imshow("before", panda)
for i in range(10, 100):
    for j in range(80, 100):
        panda.itemset((i, j), 255)
cv.imshow("after", panda)
cv.waitKey()
cv.destroyAllWindows()

img.item(3, 2) =  255
changed img.item(3, 2) =  255


## 2.2 Color images

In [18]:
img = np.random.randint(10, 99, size=[2, 4, 3], dtype = np.uint8)
print("img=\n", img)
print("img[1, 2, 0] = ", img.item(1, 2, 0))
print("img[0, 2, 1] = ", img.item(0, 2, 1))
print("img[1, 0, 2] = ", img.item(1, 0, 2))

img.itemset((1, 2, 0), 255)
img.itemset((0, 2, 1), 255)
img.itemset((1, 0, 2), 255)
print("changed img=\n", img)
print("changed img[1, 2, 0] = ", img.item(1, 2, 0))
print("changed img[0, 2, 1] = ", img.item(0, 2, 1))
print("changed img[1, 0, 2] = ", img.item(1, 0, 2))

img=
 [[[37 33 60]
  [34 46 80]
  [75 98 34]
  [65 44 60]]

 [[57 40 98]
  [13 68 87]
  [69 18 38]
  [71 59 34]]]
img[1, 2, 0] =  69
img[0, 2, 1] =  98
img[1, 0, 2] =  98
changed img=
 [[[ 37  33  60]
  [ 34  46  80]
  [ 75 255  34]
  [ 65  44  60]]

 [[ 57  40 255]
  [ 13  68  87]
  [255  18  38]
  [ 71  59  34]]]
changed img[1, 2, 0] =  255
changed img[0, 2, 1] =  255
changed img[1, 0, 2] =  255


In [19]:
img=np.random.randint(0,256,size=[256,256,3],dtype=np.uint8)
cv.imshow("demo", img)
cv.waitKey()
cv.destroyAllWindows()

In [22]:
panda = cv.imread("picture/panda.jpg")
cv.imshow("before",panda)
print("panda.item(0,0,0)=",panda.item(0,0,0))
print("panda.item(0,0,1)=",panda.item(0,0,1))
print("panda.item(0,0,2)=",panda.item(0,0,2))
for i in range(0,50):
    for j in range(0,100):
        for k in range(0,3):
            panda.itemset((i,j,k),255)
cv.imshow("after",panda)
print("changed panda.item(0,0,0)=",panda.item(0,0,0))
print("changed panda.item(0,0,1)=",panda.item(0,0,1))
print("changed panda.item(0,0,2)=",panda.item(0,0,2))
cv.waitKey()
cv.destroyAllWindows()

panda.item(0,0,0)= 255
panda.item(0,0,1)= 255
panda.item(0,0,2)= 255
changed panda.item(0,0,0)= 255
changed panda.item(0,0,1)= 255
changed panda.item(0,0,2)= 255


# 3. Region of Interest (ROI)

In [26]:
copy = cv.imread("picture/panda.jpg",cv.IMREAD_UNCHANGED)
face = copy[200:700,200:800]
cv.imshow("orginal", copy)
cv.imshow("face", face)
cv.waitKey()
cv.destroyAllWindows()

In [28]:
# Mosaic
copy = cv.imread("picture/panda.jpg",cv.IMREAD_UNCHANGED)
cv.imshow("original",copy)
face=np.random.randint(0,256,(600,600,3))
copy[100:700,200:800]=face
cv.imshow("result",copy)
cv.waitKey()
cv.destroyAllWindows()

In [33]:
# Covering the panda's face with the shark
panda=cv.imread("picture/panda.jpg",cv.IMREAD_UNCHANGED)
shark=cv.imread("picture/shark.jpg",cv.IMREAD_UNCHANGED)
cv.imshow("panda",panda)
cv.imshow("shark",shark)
face=panda[100:700,200:800]
shark[100:700,300:900]=face
cv.imshow("result",shark)
cv.waitKey()
cv.destroyAllWindows()

# 4. Channel

## 4.1 Split

In [35]:
panda=cv.imread("picture/panda.jpg")
cv.imshow("panda",panda)
b=panda[:,:,0]
g=panda[:,:,1]
r=panda[:,:,2]
cv.imshow("b",b)
cv.imshow("g",g)
cv.imshow("r",r)
panda[:,:,0]=0
cv.imshow("panda_b0",panda)
panda[:,:,1]=0
cv.imshow("panda_b0g0",panda)
cv.waitKey()
cv.destroyAllWindows()

In [36]:
panda=cv.imread("picture/panda.jpg")
b,g,r=cv.split(panda)
cv.imshow("B",b)
cv.imshow("G",g)
cv.imshow("R",r)
cv.waitKey()
cv.destroyAllWindows()

## 4.2 merge

In [37]:
panda=cv.imread("picture/panda.jpg")
b,g,r=cv.split(panda)
bgr=cv.merge([b,g,r])
rgb=cv.merge([r,g,b])
cv.imshow("panda",panda)
cv.imshow("bgr",bgr)
cv.imshow("rgb",rgb)
cv.waitKey()
cv.destroyAllWindows()

# 5. Properties

In [40]:
gray=cv.imread("picture/panda.jpg",0)
color=cv.imread("picture/panda.jpg")
print("Properties of gray: ")
print("gray.shape=",gray.shape)
print("gray.size=",gray.size)
print("gray.dtype=",gray.dtype)
print("Properties of color: ")
print("color.shape=",color.shape)
print("color.size=",color.size)
print("color.dtype=",color.dtype)

Properties of gray: 
gray.shape= (960, 960)
gray.size= 921600
gray.dtype= uint8
Properties of color: 
color.shape= (960, 960, 3)
color.size= 2764800
color.dtype= uint8
