# 1. Image reading

In [1]:
import cv2 as cv
import matplotlib as plt
import numpy as np

## 1.1 Reading BGR diagrams

In [2]:
img = cv.imread('picture/3.jpg') # BGR
print(type(img))
print(img.shape) # (h, w, c)
print(img)

<class 'numpy.ndarray'>
(960, 960, 3)
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[249 254 253]
  [249 254 253]
  [249 254 253]
  ...
  [246 255 252]
  [248 255 252]
  [248 255 252]]

 [[255 252 254]
  [253 252 254]
  [253 253 253]
  ...
  [248 255 252]
  [249 254 252]
  [249 254 252]]

 [[255 250 252]
  [253 250 252]
  [253 251 251]
  ...
  [248 255 252]
  [249 254 252]
  [251 254 252]]]


## 1.2 Read grayscale diagrams

In [3]:
img_gray = cv.imread('picture/3.jpg', cv.IMREAD_GRAYSCALE)
print(img_gray)
print('img_gray.type: ', type(img_gray))
print('img_gray.size: ', img_gray.size) # 960 * 960 = 921600
print('img_gray.dtype: ', img_gray.dtype) # uint8 means unsigned 8-bit integer
print('img_gray.shape: ', img_gray.shape)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [253 253 253 ... 253 253 253]
 [253 253 253 ... 253 253 253]
 [251 251 251 ... 253 253 253]]
img_gray.type:  <class 'numpy.ndarray'>
img_gray.size:  921600
img_gray.dtype:  uint8
img_gray.shape:  (960, 960)


# 2. Image display

## 2.1 General method

In [4]:
img = cv.imread('picture/3.jpg') # Default is BGR format
cv.imshow('fat_shark', img)
cv.waitKey(0) # Waiting time (in milliseconds)
cv.destroyAllWindows() # Destroy image window

## 2.2 Function method

In [37]:
def show_image(name, img):
    cv.imshow(name, img)
    cv.waitKey(0)
    cv.destroyAllWindows()

show_picture('fat_shark', img)

# 3. Save image

In [17]:
cv.imwrite('picture/3_gray.jpg', img_gray)

True

# 4. HSV colour space

H - 色调 Hue (dominant wavelength)\
S - 饱和度 Saturation (purity/shade of colour)\
V - 强度 Intensity

In [38]:
hsv = cv.imread('picture/3.jpg', cv.COLOR_BGR2HSV)
cv.imshow('hsv', hsv)
cv.waitKey(0)
cv.destroyAllWindows()

# 5. Extracting ROI (Region of interest)

In [24]:
img = cv.imread('picture/3.jpg')
fatshark = img[100:900, 100:900]
show_image('fatshark', fatshark)

# 6. Separate BGR channels

In [28]:
img = cv.imread('picture/3.jpg')
b, g, r = cv.split(img)
show_image('3_b', b)
print('b.shape: ', b.shape)
show_image('3_g', g)
print('g.shape: ', g.shape)
show_image('3_r', r)
print('r.shape: ', r.shape)
img = cv.merge((b, g, r))
print('img.shape: ', img.shape)

b.shape:  (960, 960)
g.shape:  (960, 960)
r.shape:  (960, 960)
img.shape:  (960, 960, 3)


In [32]:
img = cv.imread('picture/3.jpg')
b, g, r = cv.split(img)
img = cv.merge((b, g, r))

# Keep only R
fatshark_r = img.copy()
fatshark_r[:, :, 0] = 0
fatshark_r[:, :, 1] = 0
show_image('R', fatshark_r)

# Keep only G
fatshark_g = img.copy()
fatshark_g[:, :, 0] = 0
fatshark_g[:, :, 2] = 0
show_image('G', fatshark_g)

# Keep only B
fatshark_b = img.copy()
fatshark_b[:, :, 1] = 0
fatshark_b[:, :, 2] = 0
show_image('B', fatshark_b)